version: "3.9"
services:
  ms1:
    build:
      context: ./ms1Desafio03/ms1Desafio03
      dockerfile: Dockerfile
    container_name: ms1-container
    ports:
      - "8080:8080" # Porta do host para o microserviço
    depends_on:
      - mongo1
    networks:
      - ms-network

  ms2:
    build:
      context: ./ms2Desafio03/ms2Desafio03
      dockerfile: Dockerfile
    container_name: ms2-container
    ports:
      - "8081:8081" # Porta do host para o microserviço
    depends_on:
      - mongo2
    networks:
      - ms-network

  mongo1:
    image: mongo:6.0
    container_name: mongo1-container
    ports:
      - "27017:27017"
    networks:
      - ms-network
    volumes:
      - mongo1-data:/data/db

  mongo2:
    image: mongo:6.0
    container_name: mongo2-container
    ports:
      - "27018:27017"
    networks:
      - ms-network
    volumes:
      - mongo2-data:/data/db

volumes:
  mongo1-data:
  mongo2-data:

networks:
  ms-network:
    driver: bridge